[package]
name = "x86_vcpu"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.19"
cfg-if = "1.0"
bitflags = "2.2"
bit_field = "0.10"
x86 = "0.52"
x86_64 = "0.14"
raw-cpuid = "11.0"
numeric-enum-macro = "0.2"

axerrno = "0.1.0"
page_table_entry = "0.3.3"
memory_addr = "0.2.0"
crate_interface = "0.1"

axaddrspace = { git = "https://github.com/arceos-hypervisor/axaddrspace.git" }
axvcpu = { git = "https://github.com/arceos-hypervisor/axvcpu.git" }

[features]
default = ["vmx"]
vmx = []
amd = []
